name: Mirroring Repository
on:
  repository_dispatch:
    types: [mirror_repository]

jobs:
  setup_ssh:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Setup SSH Keys and known_hosts
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        - name: Some task that fetches dependencies
          env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
           git clone --bare https://github.com/felipedss/${{ github.event.client_payload.original_project_name }}.git
           cd ${{ github.event.client_payload.original_project_name }}.git
           git fetch -p origin
           git push --mirror git@github.com:felipedss/${{ github.event.client_payload.target_project_name }}.git
